### ISSUE TITLE
Cannot add this in Julia Pkg

### ISSUE THREAD

**Issue by freddycct** [AStupidBear/TrackerFlux.jl#2]
```
(tracker) pkg> add TrackerFlux
ERROR: The following package names could not be resolved:
 * TrackerFlux (not found in project, manifest or registry)
```

**Comment by freddycct** [comment]
(tracker) pkg> add TrackerFlux
ERROR: The following package names could not be resolved:
 * TrackerFlux (not found in project, manifest or registry)

**Comment by AStupidBear** [comment]
Of course, this is not registered because this should be added to Tracker.jl but no one has time to do that.

```add https://github.com/AStupidBear/TrackerFlux.jl``` is fine.
