### ISSUE TITLE
Wrong typ

### ISSUE THREAD

**Issue by freddycct** [AStupidBear/TrackerFlux.jl#3]
`ps = Flux.params(model)`

This gives Zygote.Params instead of Tracker.Params

**Comment by AStupidBear** [comment]
I know that, but luckily this won't error. So for compatibility with Zygote, I directly call `Flux.params`. Do you have an edge case?

**Comment by freddycct** [comment]
I guess having it as Zygote.Params is ok it's just not elegant, having to mix elements of Zygote when we are using Tracker.
